[[activity_wasm]]
name = "activity_llm_openai"
location = "oci://docker.io/getobelisk/demo_stargazers_activity_llm_openai:2026-07-13@sha256:fa1d7ce618228c9962662052758382a8753749332245df4a9fe242caf8faac52"
exec.lock_expiry.seconds = 10
env_vars = [{key="OPENAI_API_BASE_URL", value="${OPENAI_API_BASE_URL:-https://api.openai.com}"}]
[[activity_wasm.allowed_host]]
pattern = "${OPENAI_API_BASE_URL:-https://api.openai.com}"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["OPENAI_API_KEY"]
replace_in = ["headers"]

[[activity_wasm]]
name = "activity_github_impl"
location = "oci://docker.io/getobelisk/demo_stargazers_activity_github_impl:2026-07-13@sha256:254a9ec5557262337b323b20e9b00e8dd4c042135bda177de32a5f528e961f47"
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "https://api.github.com"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["GITHUB_TOKEN_STARGAZERS"]
replace_in = ["headers"]

[[activity_wasm]]
name = "activity_db_turso"
location = "oci://docker.io/getobelisk/demo_stargazers_activity_db_turso:2026-07-13@sha256:7eab236a25b35e1d4ae8c5cf2f01f573a7fde98499a97b172c7b4f497fd5c02c"
env_vars = ["TURSO_LOCATION"]
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "${TURSO_LOCATION}"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["TURSO_TOKEN"]
replace_in = ["headers"]

[[workflow_wasm]]
name = "workflow"
location = "oci://docker.io/getobelisk/demo_stargazers_workflow:2026-07-13@sha256:193f34f39aee1b811c76c2aad71c561e950cedaf059b5ec3909dc34f4176399d"
backtrace.sources = { ".../src/lib.rs" = "workflow/stargazers/workflow-rs/src/lib.rs" }

[[webhook_endpoint_wasm]]
name = "webhook"
location = "oci://docker.io/getobelisk/demo_stargazers_webhook:2026-07-13@sha256:86b97575b2b19b53b0c91a3fb61df5fe732d08219b98395dd6e23206be6ee9b5"
routes = [{ methods = ["POST", "GET"], route = "" }]
env_vars = [
    "GITHUB_WEBHOOK_SECRET",
    # "GITHUB_WEBHOOK_INSECURE=true" # to disable signature verification
]
backtrace.sources = { ".../src/lib.rs" = "webhook/webhook-rs/src/lib.rs" }
