[[activity_wasm]]
name = "activity_llm_openai"
location = "oci://docker.io/getobelisk/demo_stargazers_activity_llm_openai:2026-03-29@sha256:7fff6e2d50005b4cb0da3bf7b8b8aceeb05dd20af6c61e103ba2d2c182e9e8b0"
exec.lock_expiry.seconds = 10
env_vars = [{key="OPENAI_API_BASE_URL", value="${OPENAI_API_BASE_URL:-https://api.openai.com}"}]
[[activity_wasm.allowed_host]]
pattern = "${OPENAI_API_BASE_URL:-https://api.openai.com}"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["OPENAI_API_KEY"]
replace_in = ["headers"]

[[activity_wasm]]
name = "activity_github_impl"
location = "oci://docker.io/getobelisk/demo_stargazers_activity_github_impl:2026-03-29@sha256:a1f601f52ef6b93801503233600b3913d50ecbffc78e1d2046e13548615fcc12"
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "https://api.github.com"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["GITHUB_TOKEN"]
replace_in = ["headers"]

[[activity_wasm]]
name = "activity_db_turso"
location = "oci://docker.io/getobelisk/demo_stargazers_activity_db_turso:2026-03-29@sha256:cfc314fd849817b0057094859b3a58009e7024b97fcc124a757d593aa169ddfb"
env_vars = ["TURSO_LOCATION"]
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "${TURSO_LOCATION}"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["TURSO_TOKEN"]
replace_in = ["headers"]

[[workflow_wasm]]
name = "workflow"
location = "oci://docker.io/getobelisk/demo_stargazers_workflow:2026-03-29@sha256:73b30ab6bf627b1751a5491fb8cdd6ebb7764a3391f4d1270e6407e8bf5ae3e1"
backtrace.sources = { "/home/runner/work/demo-stargazers/demo-stargazers/workflow/stargazers/workflow-rs/src/lib.rs" = "${DEPLOYMENT_DIR}/workflow/stargazers/workflow-rs/src/lib.rs" }

[[webhook_endpoint_wasm]]
name = "webhook"
location = "oci://docker.io/getobelisk/demo_stargazers_webhook:2026-03-29@sha256:ac3ec877fed6557bcb2c45f7f9cc6582e4fa906e98b489055f4204c0b91e69cd"
routes = [{ methods = ["POST", "GET"], route = "" }]
env_vars = [
    "GITHUB_WEBHOOK_SECRET",
    # "GITHUB_WEBHOOK_INSECURE=true" # to disable signature verification
]
backtrace.sources = { "/home/runner/work/demo-stargazers/demo-stargazers/webhook/webhook-rs/src/lib.rs" = "${DEPLOYMENT_DIR}/webhook/webhook-rs/src/lib.rs" }

