[[activity_wasm]]
name = "activity_llm_openai"
location = "oci://docker.io/getobelisk/demo_stargazers_activity_llm_openai:2026-04-08@sha256:52767bbc9d9748af971438e853edf8438e886994cefa1f6756cde7b4de347912"
exec.lock_expiry.seconds = 10
env_vars = [{key="OPENAI_API_BASE_URL", value="${OPENAI_API_BASE_URL:-https://api.openai.com}"}]
[[activity_wasm.allowed_host]]
pattern = "${OPENAI_API_BASE_URL:-https://api.openai.com}"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["OPENAI_API_KEY"]
replace_in = ["headers"]

[[activity_wasm]]
name = "activity_github_impl"
location = "oci://docker.io/getobelisk/demo_stargazers_activity_github_impl:2026-04-08@sha256:14df5892af6e701b864668e0d11c8db51c5ec4677037c8066a77b3f99a1cf26d"
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "https://api.github.com"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["GITHUB_TOKEN_STARGAZERS"]
replace_in = ["headers"]

[[activity_wasm]]
name = "activity_db_turso"
location = "oci://docker.io/getobelisk/demo_stargazers_activity_db_turso:2026-04-08@sha256:6fafabb15c5468d7970acf0b66beec6e41bea26c96f6de148a32e00d14fdedad"
env_vars = ["TURSO_LOCATION"]
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "${TURSO_LOCATION}"
methods = ["POST"]
[activity_wasm.allowed_host.secrets]
env_vars = ["TURSO_TOKEN"]
replace_in = ["headers"]

[[workflow_wasm]]
name = "workflow"
location = "oci://docker.io/getobelisk/demo_stargazers_workflow:2026-04-08@sha256:78caee35dab856009460b012e69e3407edf9f50b4031909cb003f223f9039d8f"
backtrace.sources = { "/home/runner/work/demo-stargazers/demo-stargazers/workflow/stargazers/workflow-rs/src/lib.rs" = "${DEPLOYMENT_DIR}/workflow/stargazers/workflow-rs/src/lib.rs" }

[[webhook_endpoint_wasm]]
name = "webhook"
location = "oci://docker.io/getobelisk/demo_stargazers_webhook:2026-04-08@sha256:a14e1a4946b467a73057717bcbd4a7879b2892b146b30c5d559d5e7ed952d130"
routes = [{ methods = ["POST", "GET"], route = "" }]
env_vars = [
    "GITHUB_WEBHOOK_SECRET",
    # "GITHUB_WEBHOOK_INSECURE=true" # to disable signature verification
]
backtrace.sources = { "/home/runner/work/demo-stargazers/demo-stargazers/webhook/webhook-rs/src/lib.rs" = "${DEPLOYMENT_DIR}/webhook/webhook-rs/src/lib.rs" }

