api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui will listen.

[log.stdout]
enabled = true

[[activity_wasm]]
name = "activity_llm_chatgpt"
location.path = "target/wasm32-wasip2/release/activity_llm_chatgpt.wasm"
exec.lock_expiry.secs = 10
env_vars = ["OPENAI_API_KEY"]

[[activity_wasm]]
name = "activity_account_github"
location.path = "target/wasm32-wasip2/release/activity_account_github.wasm"
env_vars = ["GITHUB_TOKEN"]
exec.lock_expiry.secs = 5

[[activity_wasm]]
name = "activity_db_turso"
location.path = "target/wasm32-wasip2/release/activity_db_turso.wasm"
env_vars = ["TURSO_TOKEN", "TURSO_LOCATION"]

[[workflow]]
name = "workflow"
location.path = "target/wasm32-unknown-unknown/release/workflow.wasm"

[[http_server]]
name = "webhook_server"
listening_addr = "0.0.0.0:9090"

[[webhook_endpoint]]
name = "webhook"
location.path = "target/wasm32-wasip2/release/webhook.wasm"
http_server = "webhook_server"
routes = [{ methods = ["POST", "GET"], route = "" }]
forward_stdout = "stderr"
forward_stderr = "stderr"
env_vars = [
    "GITHUB_WEBHOOK_SECRET",
    # "GITHUB_WEBHOOK_INSECURE=true" to disable signature verification
]
