package stargazers:workflow-impl;

world any {
    export stargazers:workflow/workflow;

    // Import the implemented interface for `backfill`
    import stargazers:workflow/workflow;
    import stargazers:workflow-obelisk-ext/workflow;
    // activities
    import stargazers:github/account;
    import stargazers:github-obelisk-ext/account;
    import stargazers:db/llm;
    import stargazers:db-obelisk-ext/llm;
    import stargazers:db/user;
    import stargazers:db-obelisk-ext/user;
    import stargazers:llm/llm;
    import stargazers:llm-obelisk-ext/llm;
    // host provided activities for workflows
    import obelisk:workflow/workflow-support@1.0.0;
}
