package stargazers:workflow-impl;

world any {
    export stargazers:workflow/workflow;

    import stargazers:account/account;
    import stargazers:db/prompt;
    import stargazers:db/user;
    import stargazers:llm/llm;
}
