package stargazers:db;

interface user {
    /// Sender has stared a repo.
    link: func(sender: string, repo: string);
    /// Sender has unstarred a repo. Delete the sender if there are no other relations.
    unlink: func(sender: string, repo: string);
    /// Update the description of a user.
    /// User must exist at this point, if not, the operation should fail.
    user-update: func(username: string, description: option<string>);
}

interface prompt {
    get: func() -> string;
}
