[build]
target = "wasm32-wasip2"

[target.wasm32-wasip2]
runner = "wasmtime run -Scli -Shttp  --env TEST_GITHUB_TOKEN --env TEST_GITHUB_LOGIN --env TEST_GITHUB_REPO --env TEST_GITHUB_STARGAZERS_CURSOR"
