package stargazers:workflow;

interface workflow {

    /// Called by the GitHub webhook when a star is added to a repository.
    star-added: func(login: string, repo: string)  -> result<_, string>;

    /// Parallel version of `star-added`.
    star-added-parallel: func(login: string, repo: string)  -> result<_, string>;

    /// Called by the GitHub webhook when a star is removed from a repository.
    star-removed: func(login: string, repo: string) -> result<_, string>;

    /// This workflow lists the current stargazers of a repository and calls `star-added` for each of them.
    backfill: func(repo: string) -> result<_, string>;

    /// Parallel version of `backfill`.
    backfill-parallel: func(repo: string) -> result<_, string>;
}
