package stargazers:workflow;

interface workflow {
    star-added: func(sender: string, repo: string)  -> result<_, string>;
    star-removed: func(sender: string, repo: string) -> result<_, string>;
}
