package stargazers:webhook;

world any {
    // Import the workflow -schedule interface for scheduling `star_added`, `star_removed` executions.
    import stargazers:workflow-obelisk-schedule/workflow;
    // Import the database action for running `list-stargazers`.
    import stargazers:db/user;
}
