package root:component;

world root {
    import wasi:cli/environment@0.2.3;
    import obelisk:log/log@1.0.0;
    
    // HTTP client imports are added automatically.
    // import wasi:http/types@0.2.3;
    // import wasi:http/outgoing-handler@0.2.3;

    include stargazers:llm/exports;
}
