name: Cache Nix Store
on:
  push:
    paths:
      - "flake.lock" # Trigger only when flake.lock changes
  pull_request:

defaults:
  run:
    shell: bash -xe {0}

jobs:
  cache-nix-store:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Compute cache key
        id: cache-key
        run: echo "key=$(sha256sum flake.lock | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Restore cached Nix store
        uses: actions/cache@v4
        id: nix-cache
        with:
          path: /nix/store
          key: nix-store-${{ env.key }}

      - name: Install Nix
        if: steps.nix-cache.outputs.cache-hit != 'true'
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
            substituters = https://cache.nixos.org/ https://cache.garnix.io

      - name: Populate the nix store
        if: steps.nix-cache.outputs.cache-hit != 'true'
        run: nix develop --command echo

      - name: Save Nix store cache
        if: steps.nix-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: nix-store-${{ env.key }}
