name: check-test
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -xe {0}

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v29
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_conf: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}

      - name: Populate the nix store
        run: nix develop --command echo

      - name: Build tests
        run: nix develop --command cargo nextest run --workspace --all-features --no-run

      - name: cargo test
        env:
          CI: true
        run: nix develop --command cargo nextest run --workspace --all-features --profile ci-unit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test results
          files: |
            target/nextest/ci-unit/junit.xml
