name: check-verify
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -xe {0}

jobs:
  verify:
    runs-on: ubuntu-24.04
    needs: cache-nix-store
    steps:
      - uses: actions/checkout@v4

      - name: Compute cache key
        id: cache-key
        run: echo "key=$(sha256sum flake.lock | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
            substituters = https://cache.nixos.org/ https://cache.garnix.io

      - name: Restore cached Nix store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: nix-store-${{ env.key }}

      - name: Build WASM components
        run: nix develop --command cargo build

      - name: Verify obelisk-local.toml
        run: |
          nix develop --command obelisk server verify --config obelisk-local.toml --ignore-missing-env-vars

      - name: Verify obelisk-oci.toml
        run: |
          nix develop --command obelisk server verify --config obelisk-oci.toml --ignore-missing-env-vars
