name: check-verify
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -xe {0}

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v29

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}

      - name: Populate the nix store
        run: nix develop --command echo

      - name: Build WASM components
        run: nix develop --command cargo build

      - name: Verify obelisk-local.toml
        run: |
          nix develop --command obelisk server verify --config obelisk-local.toml --ignore-missing-env-vars

      - name: Verify obelisk-oci.toml
        run: |
          nix develop --command obelisk server verify --config obelisk-oci.toml --ignore-missing-env-vars
