name: check
permissions:
  contents: read

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -xe {0}

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-24.04
    needs: cache-nix-store
    steps:
      - uses: actions/checkout@v4

      - name: Compute cache key
        id: cache-key
        run: echo "key=$(sha256sum flake.lock | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
            substituters = https://cache.nixos.org/ https://cache.garnix.io

      - name: Restore cached Nix store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: nix-store-${{ env.key }}

      - name: cargo fmt
        run: nix develop --command cargo fmt --check
  check-dev-deps:
    name: Check dev-deps
    runs-on: ubuntu-latest
    needs: cache-nix-store
    steps:
      - uses: actions/checkout@v4

      - name: Compute cache key
        id: cache-key
        run: echo "key=$(sha256sum flake.lock | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
            substituters = https://cache.nixos.org/ https://cache.garnix.io

      - name: Restore cached Nix store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: nix-store-${{ env.key }}

      - run: nix develop --command ./scripts/dev-deps.sh

      - run: cat dev-deps.txt

      - run: |
          if git diff --quiet -- dev-deps.txt; then
              echo "No changes in dev-deps"
          else
              echo "Changes in dev-deps detected:"
              echo "$(git diff -- dev-deps.txt)"
              exit 1
          fi
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    needs: cache-nix-store
    steps:
      - uses: actions/checkout@v4

      - name: Compute cache key
        id: cache-key
        run: echo "key=$(sha256sum flake.lock | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
            substituters = https://cache.nixos.org/ https://cache.garnix.io

      - name: Restore cached Nix store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: nix-store-${{ env.key }}

      - name: cargo clippy
        run: nix develop --command cargo clippy --workspace --all-targets -- -D warnings
