name: check-test-integration
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (branch or SHA) to process"
        required: false
        type: string

concurrency:
  group: global-singleton
  cancel-in-progress: false

defaults:
  run:
    shell: bash -xe {0}

jobs:
  integration-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }} # Use the ref if provided, otherwise defaults to the current branch/commit

      - uses: nixbuild/nix-quick-install-action@v29
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_conf: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}

      - name: Populate the nix store
        run: nix develop --command echo

      - name: Run integration tests
        env:
          CI: true
          TEST_OPENAI_API_KEY: ${{ secrets.TEST_OPENAI_API_KEY }}
          TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          TEST_GITHUB_LOGIN: ${{ secrets.TEST_GITHUB_LOGIN }}
          TEST_GITHUB_REPO: ${{ secrets.TEST_GITHUB_REPO }}
          TEST_TURSO_TOKEN: ${{ secrets.TEST_TURSO_TOKEN }}
          TEST_TURSO_LOCATION: ${{ secrets.TEST_TURSO_LOCATION }}

        run: nix develop --command ./scripts/test-integration.sh
